DROP TABLE IF EXISTS key_operations;
DROP TYPE IF EXISTS key_operation_action;
DROP TYPE IF EXISTS key_operation_status;
DROP TABLE IF EXISTS account_telegram_links;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS servers;
DROP TABLE IF EXISTS subscriptions;
