services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sdvpn_api
    restart: always
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
    networks:
      - sdvpn_network

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: sdvpn_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - sdvpn_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: sdvpn_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - sdvpn_network

  nginx:
    image: nginx:alpine
    container_name: sdvpn_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - api
      - frontend
    networks:
      - sdvpn_network

networks:
  sdvpn_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
