services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b2b_api
    restart: always
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
    networks:
      - b2b_network

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: b2b_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        - "5555:5432"
    networks:
      - bot-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: b2b_frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - bot-network


networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local