services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b2b_api
    restart: always
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - b2b_network

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: b2b_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - b2b_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: b2b_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - b2b_network

  nginx:
    image: nginx:alpine
    container_name: b2b_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    networks:
      - b2b_network

  minio:
    image: minio/minio:latest
    container_name: b2b_minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    volumes:
      - minio_data:/data
    networks:
      - b2b_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: b2b_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - b2b_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  email_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b2b_email_worker
    command: python -m src.workers.email_worker
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - b2b_network


networks:
  b2b_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local